export const QueryKeys = {
  clientes: (filters?: Record<string, string>) => ['clientes', filters].filter(Boolean),
  clientesPago: () => ['clientes-pago'],
  usuarios: () => ['usuarios'],
  membresias: () => ['membresias'],
  pagos: (idCliente?: number) => ['pagos', idCliente].filter(Boolean),
  asignaciones: (idCliente?: number) => ['asignaciones', idCliente].filter(Boolean),
  notificaciones: (tipo?: string) => ['notificaciones', tipo].filter(Boolean),
  notificacionesContar: () => ['notificaciones', 'contar'],
  transferencias: (id?: number) => ['transferencias', id].filter(Boolean),
  transferenciasIndicadores: () => ['transferencias', 'indicadores'],
  dashboardAdmin: () => ['dashboard', 'admin'],
  dashboardRecepcion: () => ['dashboard', 'recepcion'],
  dashboardEntrenador: () => ['dashboard', 'entrenador'],
  ejercicios: () => ['ejercicios'],
  mediaEjercicios: (query: string) => ['ejercicios', 'media', query],
  rutinas: (filtros?: Record<string, string>) => ['rutinas', filtros].filter(Boolean),
  rutina: (id: number) => ['rutinas', id],
  asignacionesRutina: (id: number) => ['rutinas', id, 'asignaciones'],
  asistencias: (filtros?: Record<string, unknown>) => ['asistencias', filtros].filter(Boolean),
  asistenciasHoy: () => ['asistencias', 'hoy'],
  reportes: {
    ingresosMensuales: () => ['reportes', 'ingresos-mensuales'],
    nuevosClientes: () => ['reportes', 'nuevos-clientes'],
    distribucionMembresias: () => ['reportes', 'distribucion-membresias'],
    metodosPago: () => ['reportes', 'metodos-pago'],
    clientesActivosInactivos: () => ['reportes', 'clientes-activos-inactivos'],
    asistencias: () => ['reportes', 'asistencias'],
    asistenciasPorHora: () => ['reportes', 'asistencias-por-hora'],
    ingresosDiarios: () => ['reportes', 'ingresos-diarios'],
  },
} as const

type ExtractQueryKey<T> = T extends (...args: unknown[]) => infer R ? R : never
export type QueryKeyType = ExtractQueryKey<(typeof QueryKeys)[keyof typeof QueryKeys]>
